deploy_dbt_course:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: PBRDOGJ-XV10349

      # User/password auth
      user: prkorat
      password: Arms@home1234!!!

      role: ACCOUNTADMIN
      database: TPCDS_DATA
      warehouse: TRANSFORMING
      # in the future you should switch this schema to use a new environment variable
      # definitely switch this to your schema though
      schema: dev_schema
      threads: 4
      client_session_keep_alive: False
    prod:
      type: snowflake
      account: PBRDOGJ-XV10349

      # User/password auth
      user: prkorat
      password: Arms@home1234!!!

      role: ACCOUNTADMIN
      database: TPCDS_DATA
      warehouse: TRANSFORMING
      schema: prod_schema
      threads: 4
      client_session_keep_alive: False